### ISSUE TITLE
Host on Drupal.org or Add a Licsense and composer.json file

### ISSUE THREAD

**Issue by davidbarratt** [mediamosa/mediamosa-sdk#8]
Would you mind hosting this project on Drupal.org?
https://www.drupal.org/project/project_module

This does require that the module be licensed under GPL v2, if you don't want to do that, could you add a [license](http://choosealicense.com/) to the project?

Also, if you're not going to host on drupal.org, it would be helpful if you switched to [Semantic Versioning](http://semver.org) created a [composer.json](https://getcomposer.org/) and submit the module to [Packagist](https://packagist.org/).

Thanks!

**Comment by rblanker** [comment]
Hi David, 

The reason there is no license is included, is because its part of the MediaMosa repository (its a sub-module), which is licensed under GPLv2 and has its license under its module 'MediaMosa'. But I will include the copyright file here as well, we just forgot to put it here.

We have plans to host the MediaMosa on Drupal.org, but haven't come around it do it (yet). Can't promise anything. Will talk with MM foundation to get this going.

Been thinking about composer.json and packagist, will put this on the road map, lets see if we can put some time into that as well.

Thank you.

**Comment by davidbarratt** [comment]
@rblanker 

Thanks! Typically it's one or the other (drupal.org or packagist) until the whole drupal packagist thing is figured out, but a composer.json is always helpful. :)

Thanks!

**Comment by rblanker** [comment]
Added the license and copyright file to the SDK. Closing issue.

Thanks again.
